#!/data/data/com.termux/files/usr/bin/bash

url=$1
echo "----------Last updated Jan 24,2021----------"
str0="$(termux-dialog sheet -v "BestVideo,720p"  | jq '.text' -r)"
str1="BestVideo"
str2="720p"

if [ "$str0" == "$str1" ]; then
youtube-dlc -c -i "$url" -o "./storage/shared/Pictures/Twitter/%(title).20s.%(ext)s"
termux-media-scan -r /data/data/com.termux/files/home/storage/shared/Pictures/Twitter/

elif [ "$str0" == "$str2" ]; then
youtube-dlc -c -i "$url" -o "./storage/shared/Pictures/Twitter/%(title).20s.%(ext)s" -f 'bestvideo[height<=720]+bestaudio/best[height<=720]/best'
termux-media-scan -r /data/data/com.termux/files/home/storage/shared/Pictures/Twitter/
fi
